version: '3'
services:
    mongodb:
      build: .
      container_name: mongodb
      volumes:
        - ./data/db:/data/db
      networks:
        - java-redis
      ports:
      - 27017:27017

    redis:
      image: redis
      volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
      networks:
        - java-redis
      ports:
        - 6379:6379
networks:
  java-redis:
    driver: bridge